#!/usr/bin/env python3
"""Create a terraform.tfvars file for the AWS nut-pouring reproduction flow."""

from __future__ import annotations

import argparse
import secrets
import string
from pathlib import Path


def generate_password(length: int) -> str:
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def main():
    parser = argparse.ArgumentParser(description="Prepare AWS terraform.tfvars for the OSMO nut-pouring repro")
    parser.add_argument("--template", default="deployments/terraform/aws/example/terraform.tfvars.example")
    parser.add_argument("--output", default="deployments/terraform/aws/example/terraform.tfvars")
    parser.add_argument("--cluster-name", default="osmo")
    parser.add_argument("--aws-region", default="us-west-2")
    parser.add_argument("--owner", default="platform-team")
    parser.add_argument("--project-name", default="osmo")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing output file")
    args = parser.parse_args()

    template_path = Path(args.template).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    if output_path.exists() and not args.force:
        raise SystemExit(f"{output_path} already exists. Use --force to overwrite it.")

    text = template_path.read_text(encoding="utf-8")
    replacements = {
        'aws_region   = "us-west-2"': f'aws_region   = "{args.aws_region}"',
        'project_name = "osmo"': f'project_name = "{args.project_name}"',
        'owner        = "platform-team"': f'owner        = "{args.owner}"',
        'cluster_name = "osmo"': f'cluster_name = "{args.cluster_name}"',
        'rds_password                = "REPLACE_WITH_SECURE_PASSWORD"  # Must be changed before deployment':
            f'rds_password                = "{generate_password(24)}"  # Generated by prepare_aws_repro_tfvars.py',
        'redis_auth_token                 = "REPLACE_WITH_SECURE_PASSWORD_16_CHARS_MIN"  # Must be at least 16 characters':
            f'redis_auth_token                 = "{generate_password(24)}"  # Generated by prepare_aws_repro_tfvars.py',
    }
    for source, target in replacements.items():
        text = text.replace(source, target)

    output_path.write_text(text, encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
