# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.service.serviceName }}
  labels:
    app: {{ .Values.services.service.serviceName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.service.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.service.serviceName }}
        {{- with .Values.services.service.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.services.configs.enabled }}
        checksum/configs: {{ .Values.services.configs | toYaml | sha256sum }}
        {{- end }}
        {{- include "osmo.extra-annotations" .Values.services.service | nindent 8 }}
    spec:
      {{- with .Values.services.service.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
      {{- range .Values.services.service.topologySpreadConstraints }}
      - topologyKey: {{.topologyKey }}
        {{- range $key, $value := . }}
        {{- if ne $key "topologyKey" }}
        {{$key}}: {{$value}}
        {{- end }}
        {{- end }}
        labelSelector:
          matchLabels:
            app: {{ $.Values.services.service.serviceName }}
      {{- end }}
      nodeSelector:
        {{- range $k, $v := .Values.global.nodeSelector}}
        {{ $k }}: {{ $v }}
        {{- end}}
        {{- range $k, $v := .Values.services.service.nodeSelector}}
        {{ $k }}: {{ $v }}
        {{- end}}
      tolerations:
      {{ toYaml .Values.services.service.tolerations | nindent 8 }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      serviceAccountName: {{ include "osmo.service-account-name" (dict "serviceAccountName" .Values.services.service.serviceAccountName "Values" .Values) }}
      {{- with .Values.services.service.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.services.service.serviceName }}
        image: {{ .Values.global.osmoImageLocation }}/{{ .Values.services.service.imageName }}:{{ .Values.global.osmoImageTag }}
        command:
        - service
        args:
        - --metrics_otel_collector_component
        - {{ .Values.services.service.serviceName }}
        - --metrics_otel_enable
        - "true"
        - --redis_host
        - {{ .Values.services.redis.serviceName }}
        - --redis_port
        - {{ .Values.services.redis.port | quote }}
        - --redis_db_number
        - {{ .Values.services.redis.dbNumber | quote }}
        {{- if .Values.services.redis.tlsEnabled }}
        - --redis_tls_enable
        - "true"
        {{- end}}
        - --postgres_host
        - {{ .Values.services.postgres.serviceName }}
        - --postgres_port
        - {{ .Values.services.postgres.port | quote }}
        - --postgres_database_name
        - {{ .Values.services.postgres.db}}
        {{- if .Values.services.configFile.enabled }}
        - --mek_file
        - {{ .Values.services.configFile.path }}
        {{- end }}
        {{- if .Values.services.postgres.user }}
        - --postgres_user
        - {{ .Values.services.postgres.user }}
        {{- end }}
        {{- if .Values.services.service.auth.enabled }}
        - --device_endpoint
        - {{ .Values.services.service.auth.device_endpoint }}
        - --device_client_id
        - {{ .Values.services.service.auth.device_client_id }}
        - --browser_endpoint
        - {{ .Values.services.service.auth.browser_endpoint }}
        - --browser_client_id
        - {{ .Values.services.service.auth.browser_client_id }}
        - --token_endpoint
        - {{ .Values.services.service.auth.token_endpoint }}
        - --logout_endpoint
        - {{ .Values.services.service.auth.logout_endpoint }}
        {{- end }}
        {{- if .Values.services.service.hostname }}
        - --service_hostname
        - {{ .Values.services.service.hostname }}
        {{- end }}
        {{- if .Values.services.service.clientInstallUrl }}
        - --client_install_url
        - {{ .Values.services.service.clientInstallUrl }}
        {{- end }}
        {{- if .Values.global.osmoImageLocation }}
        - --osmo_image_location
        - {{ .Values.global.osmoImageLocation }}
        {{- end }}
        {{- if .Values.global.osmoImageTag }}
        - --osmo_image_tag
        - {{ .Values.global.osmoImageTag | quote }}
        {{- end }}
        {{- if .Values.global.logs.enabled }}
        - --log_level
        - {{ .Values.global.logs.logLevel }}
        - --k8s_log_level
        - {{ .Values.global.logs.k8sLogLevel }}
        - --log_dir
        - /logs
        - --log_name
        - api_service
        {{- end }}
        {{- if .Values.services.defaultAdmin.enabled }}
        - --default_admin_username
        - {{ .Values.services.defaultAdmin.username | quote }}
        {{- end }}
        {{- if .Values.services.configs.enabled }}
        - --config_file
        - /etc/osmo/configs/config.yaml
        {{- end }}
        {{- range $arg := .Values.services.service.extraArgs }}
        - {{ $arg | quote }}
        {{- end }}
        env:
        - name: OSMO_DISABLE_TASK_METRICS
          value: {{ .Values.services.service.disableTaskMetrics | quote }}
        {{- if .Values.services.configs.enabled }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OSMO_CONFIGMAP_NAME
          value: {{ .Values.services.service.serviceName }}-configs
        {{- end }}
        {{- if .Values.services.migration.enabled }}
        - name: OSMO_SCHEMA_VERSION
          value: {{ .Values.services.migration.targetSchema }}
        {{- end }}
        {{- include "osmo.extra-env" .Values.services.service | nindent 8 }}
        {{- if .Values.services.postgres.password }}
        - name: OSMO_POSTGRES_PASSWORD
          value: {{ .Values.services.postgres.password }}
        {{- else if .Values.services.configFile.enabled }}
        - name: OSMO_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: OSMO_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        {{- end }}
        {{- if .Values.services.defaultAdmin.enabled }}
        - name: OSMO_DEFAULT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.services.defaultAdmin.passwordSecretName }}
              key: {{ .Values.services.defaultAdmin.passwordSecretKey }}
        {{- end }}
        imagePullPolicy: {{ .Values.services.service.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1001
        ports:
        - name: metrics
          containerPort: 9464
        {{- if or .Values.services.configFile.enabled .Values.global.logs.enabled .Values.services.configs.enabled .Values.services.service.extraVolumeMounts }}
        volumeMounts:
        {{- end }}
        {{- if .Values.services.configFile.enabled}}
        - mountPath: {{ .Values.services.configFile.path }}
          name: mek-volume
          subPath: mek.yaml
        {{- end }}
        {{- if .Values.services.configs.enabled }}
        - name: configs
          mountPath: /etc/osmo/configs
          readOnly: true
        {{- range .Values.services.configs.secretRefs }}
        - name: secret-{{ .secretName }}
          mountPath: /etc/osmo/secrets/{{ .secretName }}
          readOnly: true
        {{- end }}
        {{- end }}
        {{- if .Values.global.logs.enabled }}
        - name: logs
          mountPath: /logs
        {{- end }}
        {{- include "osmo.extra-volume-mounts" .Values.services.service | nindent 8 }}
        resources:
        {{- toYaml .Values.services.service.resources | nindent 10 }}

        # Any failure to return the version api means the service is in a bad state
        livenessProbe:
        {{- toYaml .Values.services.service.livenessProbe | nindent 10 }}


        # Give the container 30 seconds to startup
        startupProbe:
          httpGet:
            port: 8000
            path: /api/version
          failureThreshold: 6
          periodSeconds: 5
          timeoutSeconds: 3
          initialDelaySeconds: 5

        # Do a basic database read operation to ensure the service is able to serve traffic
        readinessProbe:
          httpGet:
            port: 8000
            path: /api/workflow?limit=0&all_pools=true
            httpHeaders:
            - name: x-osmo-roles
              value: osmo-admin
          periodSeconds: 45
          failureThreshold: 3
          timeoutSeconds: 20

      {{- include "osmo.extra-sidecars" .Values.services.service | nindent 6 }}
      volumes:
        {{- include "osmo.extra-volumes" .Values.services.service | nindent 8 }}
        {{- if .Values.global.logs.enabled }}
        - name: logs
          emptyDir: {}
        {{- end}}
        {{- if .Values.services.configFile.enabled}}
        - configMap:
            defaultMode: 420
            items:
            - key: mek.yaml
              path: mek.yaml
            name: mek-config
          name: mek-volume
        {{- end}}
        {{- if .Values.services.configs.enabled }}
        - name: configs
          configMap:
            name: {{ .Values.services.service.serviceName }}-configs
        {{- range .Values.services.configs.secretRefs }}
        - name: secret-{{ .secretName }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
        {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.service.serviceName }}
  labels:
    app: {{ .Values.services.service.serviceName }}
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.service.serviceName }}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.services.service.serviceName }}
  labels:
    app: {{ .Values.services.service.serviceName }}
  annotations:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.service.serviceName }}
  minReplicas: {{ .Values.services.service.scaling.minReplicas }}
  maxReplicas: {{ .Values.services.service.scaling.maxReplicas }}
  metrics:
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ .Values.services.service.serviceName }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.service.scaling.hpaMemoryTarget }}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Values.services.service.serviceName }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.service.scaling.hpaCpuTarget }}
  {{- with .Values.services.service.scaling.customMetrics }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
