# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.services.configs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.service.serviceName }}-configs
  labels:
    app: {{ .Values.services.service.serviceName }}
data:
  config.yaml: |
    {{- $cfg := .Values.services.configs }}
    {{- if $cfg.service }}
    service:
      {{- $service := deepCopy $cfg.service }}
      {{- if and (not (index $service "service_base_url")) .Values.services.service.hostname }}
      {{- $_ := set $service "service_base_url" (printf "https://%s" .Values.services.service.hostname) }}
      {{- end }}
      {{- toYaml $service | nindent 6 }}
    {{- end }}
    {{- if $cfg.workflow }}
    workflow:
      {{- toYaml $cfg.workflow | nindent 6 }}
    {{- end }}
    {{- if $cfg.dataset }}
    dataset:
      {{- toYaml $cfg.dataset | nindent 6 }}
    {{- end }}
    {{- if $cfg.pools }}
    pools:
      {{- toYaml $cfg.pools | nindent 6 }}
    {{- end }}
    {{- if $cfg.podTemplates }}
    pod_templates:
      {{- toYaml $cfg.podTemplates | nindent 6 }}
    {{- end }}
    {{- if $cfg.resourceValidations }}
    resource_validations:
      {{- toYaml $cfg.resourceValidations | nindent 6 }}
    {{- end }}
    {{- if $cfg.backends }}
    backends:
      {{- toYaml $cfg.backends | nindent 6 }}
    {{- end }}
    {{- if $cfg.backendTests }}
    backend_tests:
      {{- toYaml $cfg.backendTests | nindent 6 }}
    {{- end }}
    {{- if $cfg.groupTemplates }}
    group_templates:
      {{- toYaml $cfg.groupTemplates | nindent 6 }}
    {{- end }}
    {{- if $cfg.roles }}
    roles:
      {{- toYaml $cfg.roles | nindent 6 }}
    {{- end }}
{{- end }}
