#!/usr/bin/env python3
"""
SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0

Export OSMO configs from a running instance to Helm values YAML format.

This script connects to an OSMO instance via its API and exports all
configuration into the format expected by the Helm chart's
services.configs section. Users can paste the output into their
Helm values file to migrate from DB-based to ConfigMap-based config.

Usage:
    export OSMO_URL=https://osmo.example.com
    export OSMO_TOKEN=<access-token>
    python3 export_configs_to_helm.py > my-configs.yaml

    # Or with osmo CLI auth:
    python3 export_configs_to_helm.py --url https://osmo.example.com

Environment variables:
    OSMO_URL      Base URL of the OSMO service (required)
    OSMO_TOKEN    Access token for authentication (optional if using
                  --header for custom auth)
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

import yaml


# Runtime-generated fields that should NOT be in the ConfigMap.
# These are auto-generated by configure_app() on startup.
SERVICE_RUNTIME_FIELDS = {
    'service_auth',
    'service_base_url',
}

# Runtime fields on backends written by the agent, not by config.
BACKEND_RUNTIME_FIELDS = {
    'k8s_uid',
    'k8s_namespace',
    'version',
    'last_heartbeat',
    'created_date',
    'online',
}

# Computed fields on pools that are derived, not configured.
POOL_COMPUTED_FIELDS = {
    'status',
    'last_heartbeat',
    'parsed_resource_validations',
    'parsed_pod_template',
    'parsed_group_templates',
}

# Computed fields on platforms within pools. These are resolved at runtime
# from template/validation name references (override_pod_template,
# resource_validations, common_pod_template, common_resource_validations).
PLATFORM_COMPUTED_FIELDS = {
    'parsed_resource_validations',
    'parsed_pod_template',
    'parsed_group_templates',
    'tolerations',
    'labels',
    'default_mounts',
}

# Fields on roles that are internal metadata, not config.
ROLE_INTERNAL_FIELDS = {
    'sync_mode',
}


def fetch(base_url, path, headers):
    """Fetch JSON from the OSMO API."""
    url = f'{base_url}{path}'
    parsed = urllib.parse.urlsplit(url)
    if parsed.scheme not in ('http', 'https'):
        print(f'Error: URL must use http or https scheme: {url}',
              file=sys.stderr)
        return None
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as error:
        print(f'Error fetching {path}: HTTP {error.code}', file=sys.stderr)
        try:
            body = error.read().decode()
            print(f'  {body[:200]}', file=sys.stderr)
        except Exception as read_error:
            print(f'  (Could not read error body: {read_error})',
                  file=sys.stderr)
        return None
    except urllib.error.URLError as error:
        print(f'Error connecting to {url}: {error.reason}', file=sys.stderr)
        return None


def strip_fields(data, fields):
    """Remove specified keys from a dict."""
    if not isinstance(data, dict):
        return data
    return {k: v for k, v in data.items() if k not in fields}


def export_singleton(base_url, headers, config_type, strip):
    """Export a singleton config (service, workflow, dataset)."""
    data = fetch(base_url, f'/api/configs/{config_type}', headers)
    if data is None:
        return None
    data = strip_fields(data, strip)
    # Remove _configmap_mode flag if present
    data.pop('_configmap_mode', None)
    return data


def export_backends(base_url, headers):
    """Export backends, stripping runtime fields."""
    data = fetch(base_url, '/api/configs/backend', headers)
    if data is None:
        return None

    backends_list = data.get('backends', data)
    if isinstance(backends_list, list):
        items = {}
        for backend in backends_list:
            name = backend.pop('name', None)
            if name:
                items[name] = strip_fields(backend, BACKEND_RUNTIME_FIELDS)
        return items
    return None


def strip_platform_computed_fields(pool):
    """Strip computed fields from each platform within a pool."""
    platforms = pool.get('platforms')
    if not isinstance(platforms, dict):
        return
    for platform_data in platforms.values():
        if isinstance(platform_data, dict):
            for field in PLATFORM_COMPUTED_FIELDS:
                platform_data.pop(field, None)


def export_pools(base_url, headers):
    """Export pools in editable format, stripping computed fields."""
    data = fetch(base_url, '/api/configs/pool?verbose=true', headers)
    if data is None:
        return None

    pools_data = data.get('pools', data)
    if isinstance(pools_data, dict):
        items = {}
        for name, pool in pools_data.items():
            if isinstance(pool, dict):
                clean = strip_fields(pool, POOL_COMPUTED_FIELDS | {'name'})
                strip_platform_computed_fields(clean)
                items[name] = clean
            elif isinstance(pool, list):
                for pool_item in pool:
                    pool_name = pool_item.pop('name', name)
                    clean = strip_fields(pool_item, POOL_COMPUTED_FIELDS)
                    strip_platform_computed_fields(clean)
                    items[pool_name] = clean
        return items
    return None


def export_named_configs(base_url, headers, path):
    """Export named configs (pod_templates, resource_validations, etc.)."""
    data = fetch(base_url, f'/api/configs/{path}', headers)
    if data is None:
        return None
    return data


def export_roles(base_url, headers):
    """Export roles, stripping internal fields."""
    data = fetch(base_url, '/api/configs/role', headers)
    if data is None:
        return None

    items = {}
    for role in data:
        name = role.pop('name', None)
        if name:
            items[name] = strip_fields(role, ROLE_INTERNAL_FIELDS)
    return items


def collect_secret_names(configs):
    """Walk the config dict and collect all secretName references."""
    secrets = set()
    if not isinstance(configs, dict):
        return secrets
    for key, value in configs.items():
        if key == 'secretName' and isinstance(value, str):
            secrets.add(value)
        elif isinstance(value, dict):
            secrets.update(collect_secret_names(value))
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    secrets.update(collect_secret_names(item))
    return secrets


def main():
    parser = argparse.ArgumentParser(
        description='Export OSMO configs to Helm values YAML format.',
        epilog='Output can be pasted into services.configs in your Helm values.',
    )
    parser.add_argument(
        '--url', default=os.environ.get('OSMO_URL', ''),
        help='OSMO service base URL (or set OSMO_URL env var)')
    parser.add_argument(
        '--token', default=os.environ.get('OSMO_TOKEN', ''),
        help='Access token (or set OSMO_TOKEN env var)')
    parser.add_argument(
        '--header', action='append', default=[],
        help='Custom header (e.g., "x-osmo-user: admin"). Can be repeated.')
    args = parser.parse_args()

    if not args.url:
        parser.error('OSMO_URL or --url is required')

    base_url = args.url.rstrip('/')
    headers = {}
    if args.token:
        headers['Authorization'] = f'Bearer {args.token}'
    for header in args.header:
        key, _, value = header.partition(':')
        headers[key.strip()] = value.strip()

    print(f'# Exported from {base_url}', file=sys.stderr)
    print('# Paste this into services.configs in your Helm values.\n',
          file=sys.stderr)

    configs = {}

    # Singleton configs
    print('Exporting service config...', file=sys.stderr)
    service = export_singleton(
        base_url, headers, 'service', SERVICE_RUNTIME_FIELDS)
    if service:
        configs['service'] = service

    print('Exporting workflow config...', file=sys.stderr)
    workflow = export_singleton(base_url, headers, 'workflow', set())
    if workflow:
        configs['workflow'] = workflow

    print('Exporting dataset config...', file=sys.stderr)
    dataset = export_singleton(base_url, headers, 'dataset', set())
    if dataset:
        configs['dataset'] = dataset

    # Named configs
    print('Exporting backends...', file=sys.stderr)
    backends = export_backends(base_url, headers)
    if backends:
        configs['backends'] = backends

    print('Exporting pools...', file=sys.stderr)
    pools = export_pools(base_url, headers)
    if pools:
        configs['pools'] = pools

    # Named configs use camelCase keys to match Helm values convention.
    # The Helm chart template (configs.yaml) converts these to snake_case
    # when rendering the ConfigMap file that the loader reads.
    print('Exporting pod templates...', file=sys.stderr)
    pod_templates = export_named_configs(
        base_url, headers, 'pod_template')
    if pod_templates:
        configs['podTemplates'] = pod_templates

    print('Exporting resource validations...', file=sys.stderr)
    resource_validations = export_named_configs(
        base_url, headers, 'resource_validation')
    if resource_validations:
        configs['resourceValidations'] = resource_validations

    print('Exporting group templates...', file=sys.stderr)
    group_templates = export_named_configs(
        base_url, headers, 'group_template')
    if group_templates:
        configs['groupTemplates'] = group_templates

    print('Exporting backend tests...', file=sys.stderr)
    backend_tests = export_named_configs(
        base_url, headers, 'backend_test')
    if backend_tests:
        configs['backendTests'] = backend_tests

    print('Exporting roles...', file=sys.stderr)
    role_items = export_roles(base_url, headers)
    if role_items:
        configs['roles'] = role_items

    # Collect secret references for secretRefs
    all_secrets = collect_secret_names(configs)
    secret_refs = [{'secretName': name} for name in sorted(all_secrets)]

    # Build final output
    output = {
        'services': {
            'configs': {
                'enabled': True,
                **({'secretRefs': secret_refs} if secret_refs else {}),
                **configs,
            },
        },
    }

    yaml.dump(output, sys.stdout, default_flow_style=False, sort_keys=False)

    print(f'\nExported {len(configs)} config sections.', file=sys.stderr)
    if secret_refs:
        print(f'Found {len(secret_refs)} secret references: '
              f'{[s["secretName"] for s in secret_refs]}', file=sys.stderr)
        print('Ensure these K8s Secrets exist in your namespace.',
              file=sys.stderr)


if __name__ == '__main__':
    main()
