# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.  # pylint: disable=line-too-long
# SPDX-License-Identifier: Apache-2.0
"""Create a PR from test files generated by Claude Code.

Detects new/modified test files, creates a branch, commits, pushes,
and opens a PR with the ai-generated label. Skips if no changes or
an ai-generated PR is already open.

Usage:
    python create_pr.py
    python create_pr.py --dry-run
"""

import argparse
import datetime
import logging
import re
import subprocess
import sys

from src.scripts.testbot.guardrails import get_changed_test_files

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a command, log failures, and return the result."""
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        logger.error(
            "Command %s failed (exit %d):\nstdout: %s\nstderr: %s",
            cmd, result.returncode, result.stdout[:2000], result.stderr[:2000],
        )
        if check:
            result.check_returncode()
    return result


def has_open_testbot_pr() -> bool:
    """Check if there is already an open testbot PR.

    Filters by both label and author so that developer PRs manually
    labeled ai-generated don't block new testbot runs.
    Returns True (fail closed) if the gh command fails.
    """
    result = run(
        ["gh", "pr", "list", "--label", "ai-generated", "--state", "open",
         "--author", "svc-osmo-ci",
         "--json", "number", "--jq", "length"],
        check=False,
    )
    if result.returncode != 0:
        logger.error("gh pr list failed: %s", result.stderr[:200])
        return True
    try:
        return int(result.stdout.strip()) > 0
    except ValueError:
        return True


_SUSPECTED_BUG_RE = re.compile(r"(?:#|//)\s*SUSPECTED BUG:\s*(.+)")


def _scan_suspected_bugs(files: list[str]) -> list[str]:
    """Scan test files for SUSPECTED BUG markers left by Claude."""
    seen: set[str] = set()
    bugs: list[str] = []
    for filepath in files:
        try:
            with open(filepath, encoding="utf-8") as fh:
                for line in fh:
                    match = _SUSPECTED_BUG_RE.search(line)
                    if match:
                        description = match.group(1).strip()
                        if description not in seen:
                            seen.add(description)
                            bugs.append(description)
        except OSError:
            logger.warning("Could not read %s for bug markers", filepath)
    return bugs


def main() -> None:
    """Detect changes, create branch, commit, push, and open PR."""
    parser = argparse.ArgumentParser(
        description="Create a PR from AI-generated test files.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be done without creating a PR",
    )
    args = parser.parse_args()

    if has_open_testbot_pr():
        logger.info("An ai-generated PR is already open. Skipping to avoid stacking.")
        return

    changed_files = get_changed_test_files()
    if not changed_files:
        logger.info("No test files generated, nothing to commit.")
        return

    logger.info("Changed test files: %s", changed_files)

    basenames = sorted({f.rsplit("/", maxsplit=1)[-1] for f in changed_files})
    # Strip test prefixes/suffixes to show source file names in the PR title.
    # test_foo.py → foo.py, foo_test.go → foo.go, foo.test.ts → foo.ts
    source_names = sorted({
        re.sub(r"^test_", "", re.sub(r"[._]test(\.\w+)$", r"\1", name))
        for name in basenames
    })
    files_summary = ", ".join(source_names)
    files_list = "\n".join(f"- `{f}`" for f in changed_files)

    branch = f"testbot/{datetime.datetime.now(tz=datetime.timezone.utc).strftime("%Y%m%d-%H%M")}"

    if args.dry_run:
        logger.info("Dry run — would create branch '%s' with files:\n%s", branch, files_list)
        return

    run(["git", "checkout", "-b", branch])
    run(["git", "add"] + changed_files)
    subprocess.run(
        ["git", "commit", "-m", f"Add AI-generated tests for {files_summary}"],
        check=True,
    )
    push_result = run(["git", "push", "-u", "origin", branch], check=False)
    if push_result.returncode != 0:
        logger.error("Failed to push branch '%s'", branch)
        sys.exit(1)
    logger.info("Pushed branch '%s'", branch)

    suspected_bugs = _scan_suspected_bugs(changed_files)
    bugs_section = ""
    if suspected_bugs:
        bugs_list = "\n".join(f"- {bug}" for bug in suspected_bugs)
        bugs_section = f"\n## Suspected bugs\n{bugs_list}\n"

    pr_body = f"""## Summary
AI-generated tests targeting file(s) with low coverage.

Issue - None

## Files tested
{files_list}
{bugs_section}
## Checklist
- [x] I am familiar with the Contributing Guidelines
- [x] New or existing tests cover these changes
- [x] The documentation is up to date with these changes

---
Generated by testbot pipeline"""

    result = subprocess.run(
        ["gh", "pr", "create",
         "--title", f"[testbot] Add tests for {files_summary}",
         "--label", "ai-generated",
         "--base", "main",
         "--body", pr_body],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        logger.error("Failed to create PR: %s", result.stderr)
        sys.exit(1)

    logger.info("PR created: %s", result.stdout.strip())


if __name__ == "__main__":
    main()
