# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

filegroup(
    name = "workflows",
    srcs = glob(
        [
            "*.yaml",
            "*.yml",
        ],
    ),
    visibility = ["//src/scripts/testbot/tests:__pkg__"],
)
